# Generated by Django 5.1.6 on 2025-03-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_credits_course_semester_course_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], null=True),
        ),
    ]
