# Generated by Django 5.1.6 on 2025-03-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2')], null=True),
        ),
    ]
