# Generated by Django 5.1.6 on 2025-03-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_experiment_number_reference_number_topic_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='link',
        ),
    ]
